CREATE TABLE brewery(
  id INTEGER PRIMARY KEY,
  name VARCHAR (200),
  address VARCHAR (300)
);

CREATE TABLE beer (
  id         INTEGER PRIMARY KEY,
  name VARCHAR(200),
  type  VARCHAR(100),
  alcohol_content DOUBLE,
  brewery_id INTEGER,
  constraint fk_brewery foreign key(brewery_id) references brewery(id)
);


-- SECURITY SCHEMA CREATION

create table users(
	username VARCHAR_IGNORECASE(50) not null primary key,
	password VARCHAR_IGNORECASE(50) not null,
	enabled BOOLEAN not null
);

create table authorities (
	username VARCHAR_IGNORECASE(50) not null,
	authority VARCHAR_IGNORECASE(50) not null,
	constraint fk_authorities_users foreign key(username) references users(username)
);

-- ALTER TABLE authorities
-- ADD FOREIGN KEY (username) 
-- REFERENCES users(username);

create unique index ix_auth_username on authorities (username,authority);

create table groups (
	id BIGINT generated by default as IDENTITY(start with 0) primary key,
	group_name VARCHAR_IGNORECASE(50) not null
);

create table group_authorities (
	group_id BIGINT not null,
	authority VARCHAR(50) not null,
	constraint fk_group_authorities_group foreign key(group_id) references groups(id)
);

create table group_members (
	id BIGINT generated by default as IDENTITY(start with 0) primary key,
	username VARCHAR(50) not null,
	group_id BIGINT not null,
	constraint fk_group_members_group foreign key(group_id) references groups(id)
);
